name: galsim
channels:
  - conda-forge/label/gcc7
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py37_0
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alabaster=0.7.12=py_0
  - anaconda=custom=py37_1
  - anaconda-client=1.8.0=pyhd8ed1ab_0
  - anaconda-project=0.11.1=pyhd8ed1ab_0
  - anyio=3.6.1=pyhd8ed1ab_1
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37h540881e_2
  - asn1crypto=1.5.1=pyhd8ed1ab_0
  - astroid=2.12.10=py37h89c1867_0
  - astromatic-psfex=3.21.1=h4487ae1_1
  - astromatic-source-extractor=2.25.0=h4487ae1_0
  - astropy=4.3.1=py37h09021b7_0
  - atomicwrites=1.4.1=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - backports.os=0.1.1=py37h89c1867_1005
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - backports.zoneinfo=0.2.1=py37h540881e_5
  - beautifulsoup4=4.11.1=pyha770c72_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_8
  - bitarray=2.6.0=py37h540881e_0
  - bkcharts=0.2=py37h06a4308_1
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_linux64_openblas
  - bleach=5.0.1=pyhd8ed1ab_0
  - blosc=1.21.1=h83bc5f7_3
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boto=2.49.0=py_0
  - bottleneck=1.3.5=py37hda87dfa_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py37h540881e_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.14.12=h8948797_3
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.12.3=py37h2e261b9_0
  - cfitsio=4.1.0=hd9d235c_0
  - chardet=5.0.0=py37h89c1867_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py37h89c1867_0
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - clyent=1.2.2=py_1
  - colorama=0.4.5=pyhd8ed1ab_0
  - conda-pack=0.7.0=pyh6c4a22f_0
  - contextlib2=21.6.0=pyhd8ed1ab_0
  - coverage=6.5.0=py37h540881e_0
  - cryptography=38.0.1=py37h38fbfac_0
  - curl=7.85.0=h7bff187_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.32=py37hd23a5d3_0
  - cytoolz=0.12.0=py37h540881e_0
  - dask=2.4.0=py_0
  - dask-core=2.4.0=py_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.3=py37hd23a5d3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - distributed=2.4.0=py_0
  - docutils=0.19=py37h89c1867_0
  - eigen=3.3.7=hfd86e86_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - enum34=1.1.10=py37hc8dfbb8_2
  - esutil=0.6.2.5=py37h637b7d7_1000
  - et_xmlfile=1.0.1=py_1001
  - exceptiongroup=1.0.0rc9=pyhd8ed1ab_0
  - expat=2.4.9=h27087fc_0
  - fastcache=1.1.0=py37h540881e_4
  - fftw=3.3.10=nompi_hf0379b8_105
  - filelock=3.8.0=pyhd8ed1ab_0
  - fitsio=1.1.8=py37hc138621_0
  - flask=2.2.2=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.37.4=py37h540881e_0
  - freetype=2.12.1=hca18f0e_0
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2022.8.2=pyhd8ed1ab_0
  - future=0.18.2=py37h89c1867_5
  - galsim=2.2.4=py37he0bd3bc_1
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_8
  - get_terminal_size=1.0.0=haa9412d_0
  - gettext=0.19.8.1=h27087fc_1009
  - gevent=21.12.0=py37haa10bde_2
  - glib=2.56.2=had28632_1001
  - glob2=0.7=py_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py37h025e8b9_0
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=1.1.3=py37hd23a5d3_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=3.7.0=nompi_py37hf1ce037_101
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.12.2=nompi_h2386368_100
  - healpy=1.16.1=py37hc950561_0
  - heapdict=1.0.1=py_0
  - html5lib=1.1=pyh9f0ad1d_0
  - hypothesis=6.56.1=py37h89c1867_0
  - icu=58.2=hf484d3e_1000
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs-lite=2019.12.3=py37hda87dfa_5
  - imageio=2.22.0=pyhfa7a67d_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py37h89c1867_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.14.0=py37h25bab4e_0
  - ipython=7.33.0=py37h89c1867_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - isort=5.10.1=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.2.2=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jdcal=1.4.1=py_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py37h89c1867_7
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py37h89c1867_0
  - jupyter_server=1.19.1=pyhd8ed1ab_0
  - jupyterlab=3.4.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.15.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - keyring=23.9.3=py37h89c1867_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py37h7cecad7_0
  - krb5=1.19.3=h3790be6_0
  - lazy-object-proxy=1.7.1=py37h540881e_1
  - lcms2=2.12=hddcbb42_0
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.5.2=hb890918_3
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.85.0=h7bff187_0
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.2.1=h4deb6c0_3
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - liblief=0.12.2=h27087fc_0
  - libllvm11=11.1.0=he0ac6c6_4
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.38=h753d276_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h55922b4_4
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.44.2=h166bdaf_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzlib=1.2.12=h166bdaf_4
  - llvm-openmp=14.0.4=he0ac6c6_0
  - llvmlite=0.39.1=py37h0761922_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lsstdesc.coord=1.2.3=py37h7cecad7_0
  - lxml=4.9.1=py37h540881e_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - markupsafe=2.1.1=py37h540881e_1
  - matplotlib=3.5.2=py37h06a4308_0
  - matplotlib-base=3.5.2=py37hc347a89_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-service=2.4.0=py37h94185c7_0
  - mkl_fft=1.3.1=py37h90e98c2_3
  - mkl_random=1.2.2=py37h693438c_1
  - more-itertools=8.14.0=pyhd8ed1ab_0
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py37h7cecad7_0
  - multipledispatch=0.6.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.4=pyhd8ed1ab_0
  - nbclient=0.6.8=pyhd8ed1ab_0
  - nbconvert=7.1.0=pyhd8ed1ab_0
  - nbconvert-core=7.1.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.1.0=pyhd8ed1ab_0
  - nbformat=5.6.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - nltk=3.6.7=pyhd8ed1ab_0
  - nose=1.3.7=py_1006
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - numba=0.56.2=py37hf081915_1
  - numexpr=2.8.3=py37hd2a5715_0
  - numpy=1.21.5=py37hf838250_3
  - numpy-base=1.21.5=py37h1e6e340_3
  - numpydoc=1.4.0=pyhd8ed1ab_1
  - olefile=0.46=pyh9f0ad1d_1
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openjpeg=2.5.0=h7d73246_1
  - openpyxl=3.0.10=py37h540881e_1
  - openssl=1.1.1s=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.2.3=py37hdc94413_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.42.4=h049681c_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - patchelf=0.15.0=h58526e2_0
  - path=16.4.0=py37h89c1867_1
  - path.py=12.5.0=0
  - pathlib=1.0.1=py37h89c1867_6
  - pathlib2=2.3.7.post1=py37h89c1867_1
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pep8=1.7.1=py_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py37h850a105_2
  - pip=19.2.3=py37_0
  - pixman=0.40.0=h36c2ea0_0
  - pkginfo=1.8.3=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=py37h89c1867_3
  - ply=3.11=py_1
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - prompt_toolkit=3.0.31=hd8ed1ab_0
  - psutil=5.9.2=py37h540881e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py=1.11.0=pyh6c4a22f_0
  - py-lief=0.12.2=py37hd23a5d3_0
  - pybind11=2.10.0=py37h7cecad7_0
  - pybind11-global=2.10.0=py37h7cecad7_0
  - pycodestyle=2.9.1=pyhd8ed1ab_0
  - pycosat=0.6.3=py37h540881e_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pycrypto=2.6.1=py37h5e8e339_1006
  - pycurl=7.45.1=py37haaec8a5_2
  - pyerfa=2.0.0.1=py37hda87dfa_2
  - pyflakes=2.5.0=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pylint=2.15.3=pyhd8ed1ab_0
  - pyodbc=4.0.34=py37hd23a5d3_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyrsistent=0.18.1=py37h540881e_1
  - pysocks=1.7.1=py37h89c1867_5
  - pytables=3.7.0=py37h7d129aa_2
  - pytest=7.1.3=py37h89c1867_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.10.0=pyhd8ed1ab_0
  - pytest-astropy-header=0.1.2=py_0
  - pytest-cov=4.0.0=pyhd8ed1ab_0
  - pytest-doctestplus=0.12.1=pyhd8ed1ab_0
  - pytest-filter-subpackage=0.1.1=py_0
  - pytest-mock=3.9.0=pyhd8ed1ab_0
  - pytest-openfiles=0.5.0=py_0
  - pytest-remotedata=0.3.3=pyhd8ed1ab_0
  - pytest-runner=6.0.0=pyhd8ed1ab_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-libarchive-c=4.0=py37h89c1867_1
  - python_abi=3.7=2_cp37m
  - pytoolconfig=1.2.2=pyhd8ed1ab_0
  - pytz=2022.4=pyhd8ed1ab_0
  - pywavelets=1.3.0=py37hda87dfa_1
  - pyyaml=6.0=py37h540881e_4
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=1.1.1=pyhd8ed1ab_0
  - qtconsole=5.3.2=pyhd8ed1ab_0
  - qtconsole-base=5.3.2=pyha770c72_0
  - qtpy=2.2.1=pyhd8ed1ab_0
  - readline=7.0=hf8c457e_1001
  - regex=2022.9.13=py37h540881e_0
  - requests=2.28.1=pyhd8ed1ab_1
  - rope=1.3.0=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py37h540881e_1007
  - scikit-image=0.19.3=py37hfb7772e_1
  - scikit-learn=1.0.2=py37hf9e9bfc_0
  - scipy=1.7.3=py37hf2a6cf1_0
  - seaborn=0.12.0=hd8ed1ab_0
  - seaborn-base=0.12.0=pyhd8ed1ab_0
  - secretstorage=3.3.3=py37h89c1867_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=59.8.0=py37h89c1867_1
  - simplegeneric=0.8.1=py_1
  - singledispatch=3.6.1=pyh44b312d_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcollections=2.1.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=5.2.3=pyhd8ed1ab_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sphinxcontrib-websupport=1.2.4=pyhd8ed1ab_1
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlalchemy=1.4.41=py37h540881e_0
  - sqlite=3.29.0=h7b6447c_0
  - statsmodels=0.13.2=py37hda87dfa_0
  - sympy=1.10.1=py37h89c1867_1
  - tbb=2021.6.0=h924138e_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.15.0=py37h89c1867_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2019.7.26.2=py37_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.5=pyha770c72_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py37h540881e_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - treecorr=3.3.11=py37hf484d3e_1001
  - typed-ast=1.5.4=py37h540881e_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022d=h191b570_0
  - unicodecsv=0.14.1=py_1
  - unicodedata2=14.0.0=py37h540881e_1
  - unixodbc=2.3.10=h583eb01_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.1=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - wrapt=1.14.1=py37h540881e_0
  - wurlitzer=3.0.2=pyhd8ed1ab_2
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xlsxwriter=3.0.3=pyhd8ed1ab_0
  - xlwt=1.3.0=py_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_4
  - zope.event=4.5.0=pyh9f0ad1d_0
  - zope.interface=5.4.0=py37h540881e_2
  - zstd=1.5.2=h6239696_4
  - pip:
    - desmeds==0.9.7
    - images==0.1.0
    - meds==0.9.15
    - nfw==0.2.0.dev2
    - ngmix==1.3.9
    - ngmixer==v0.9.8
    - psfex==0.4.0
prefix: /home/moon/vargatn/anaconda3/envs/galsim
